[build]
  publish = "build/web"
  command = "flutter build web --release"

[build.environment]
  FLUTTER_VERSION = "3.16.0"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[context.production.environment]
  FLUTTER_WEB = "true"
  
[context.deploy-preview.environment]
  FLUTTER_WEB = "true"