[build]
  publish = "build/web"
  command = """
    # Install Flutter
    if [ ! -d "/opt/flutter" ]; then
      echo "Installing Flutter..."
      cd /opt
      curl -o flutter_linux_3.16.0-stable.tar.xz https://storage.googleapis.com/flutter_infra_release/releases/stable/linux/flutter_linux_3.16.0-stable.tar.xz
      tar xf flutter_linux_3.16.0-stable.tar.xz
      rm flutter_linux_3.16.0-stable.tar.xz
    fi
    
    # Add Flutter to PATH
    export PATH="/opt/flutter/bin:$PATH"
    
    # Verify Flutter installation
    flutter doctor
    
    # Enable web support and build
    flutter config --enable-web
    flutter pub get
    flutter build web --release
  """

[build.environment]
  FLUTTER_VERSION = "3.16.0"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[context.production.environment]
  FLUTTER_WEB = "true"
  
[context.deploy-preview.environment]
  FLUTTER_WEB = "true"