# Netlify configuration for Flutter web app
# Build is handled by GitHub Actions

[build]
  # Skip build command - handled by GitHub Actions
  publish = "build/web"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[context.production.environment]
  FLUTTER_WEB = "true"
  
[context.deploy-preview.environment]
  FLUTTER_WEB = "true"